### ISSUE TITLE
General Improvments Compatibility

### ISSUE THREAD

**Issue by FrostyCirno** [LinkTroisUn/ShipMeltdown#1]
Can you add compatibility for General Improvements monitors, as you did for Open Monitors? Would be very cool!

**Comment by LinkTroisUn** [comment]
I will try that

**Comment by LinkTroisUn** [comment]
I can tell you it works. I will soon be posting the new version

**Comment by LinkTroisUn** [comment]
Version 1.6.50 has now been pushed to Thunderstore, implementing that feature. I have made many tests, but if you encounter any problem regarding the compatibility with GeneralImprovements, you can re open this issue. If that happened, I would need an explanation of the bug (with pictures if relevant), the version of GeneralImprovements you are using, and its config file
