### ISSUE TITLE
Minor Thunderstore request

### ISSUE THREAD

**Issue by Seviper** [LinkTroisUn/ShipMeltdown#2]
On the thunderstore search, unless you specifically look under "Modpacks" category, you cannot find this mod. I believe the modpack tag for ShipMeltdown is causing this. Is it possible to set it to where the mod can be found through the Mods tab?

**Comment by LinkTroisUn** [comment]
The modpack tag is sure unexpected. I have reuploaded the mod to Thunderstore, without the modpack tag. For now, we have to wait until Thunderstore's indexes get refreshed to see if the problem has been solved

**Comment by LinkTroisUn** [comment]
Looks like it did not work. I'm not sure how to fix this if the tags don't get replaced with a reupload...

**Comment by Seviper** [comment]
Would you be alright if I bring it up to the thunderstore mods in the modding discord? I can link this thread stating that you would like your mod to listed to correctly alongside linking the mod itself.

**Comment by LinkTroisUn** [comment]
I suppose you can do that

**Comment by Seviper** [comment]
Sorry for the lateness, but I've let the moderators of thunderstore now and the issue has been fixed. The mod search now shows your mod correctly.
